apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticserver-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: staticserver
  template:
    metadata:
      labels:
        app: staticserver
    spec:
      containers:
      - name: staticserver-container
        image: staticserver:v0.1
        imagePullPolicy: Never
        volumeMounts:
        - name: config-storage
          mountPath: "/app/config"
          readOnly: true
        - name: webresource-storage
          mountPath: "/app/www"
          readOnly: true
        ports:
        - containerPort: 8080
      volumes:
      - name: config-storage
        persistentVolumeClaim:
          claimName: config-pvc
      - name: webresource-storage
        persistentVolumeClaim:
          claimName: webresource-pvc