apiVersion: v1
kind: PersistentVolume
metadata:
  name: webresource-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/docker/www